<?php
declare(strict_types=1);

return [
    'earthquakes' => [
        'provider' => 'USGS + INGV + EMSC',
        'sources' => [
            [
                'key' => 'usgs',
                'provider' => 'USGS',
                'url' => 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',
            ],
            [
                'key' => 'ingv',
                'provider' => 'INGV',
                'url' => 'https://webservices.ingv.it/fdsnws/event/1/query?format=geojson&limit=1000&orderby=time',
            ],
            [
                'key' => 'emsc',
                'provider' => 'EMSC',
                'url' => 'https://www.seismicportal.eu/fdsnws/event/1/query?format=json&limit=1000&orderby=time',
            ],
        ],
    ],
    'volcanoes' => [
        'provider' => 'Smithsonian GVP / USGS',
        'url' => 'https://volcano.si.edu/news/WeeklyVolcanoRSS.xml',
    ],
    'volcano_catalog' => [
        'provider' => 'Smithsonian GVP Volcanoes of the World',
        'url' => 'https://volcano.si.edu/database/list_volcano_holocene_excel.cfm',
    ],
    'volcano_current_eruptions' => [
        'provider' => 'Smithsonian GVP Current Eruptions',
        'url' => 'https://volcano.si.edu/gvp_currenteruptions.cfm',
    ],
    'tremors' => [
        'provider' => 'USGS (Tremor Signals Model)',
        'url' => 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',
    ],
    'tsunami' => [
        'provider' => 'NOAA / NWS',
        'url' => 'https://api.weather.gov/alerts/active?status=actual&message_type=alert',
    ],
    'weather_alerts' => [
        'provider' => 'NOAA / NWS',
        'url' => 'https://api.weather.gov/alerts/active?status=actual&message_type=alert',
    ],
    'space_weather' => [
        'provider' => 'NOAA SWPC',
        'kp_url' => 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',
        'kp_forecast_url' => 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json',
        'xray_url' => 'https://services.swpc.noaa.gov/json/goes/primary/xrays-1-day.json',
        'solar_wind_plasma_url' => 'https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json',
        'solar_wind_mag_url' => 'https://services.swpc.noaa.gov/products/solar-wind/mag-1-day.json',
        'dst_url' => 'https://services.swpc.noaa.gov/products/kyoto-dst.json',
        'magnetometers_url' => 'https://services.swpc.noaa.gov/json/goes/primary/magnetometers-1-day.json',
        'auroral_oval_url' => 'https://services.swpc.noaa.gov/images/animations/ovation/north/latest.jpg',
        'ovation_json_url' => 'https://services.swpc.noaa.gov/json/ovation_aurora_latest.json',
        'sun_image_url' => 'https://services.swpc.noaa.gov/images/animations/suvi/primary/171/latest.png',
    ],
    'volcano_cams' => [
        'provider' => 'Curated Observatory Cameras',
        'items' => [
            [
                'name' => 'Etna Live Stream',
                'volcano' => 'Etna',
                'country' => 'Italy',
                'source' => 'INGV Catania',
                'stream_url' => 'https://www.ct.ingv.it/sezioniesterne/StreamingEtna.php',
                'embed_url' => 'https://garr.tv/videos/embed/c6c70a03-e711-4eed-9835-1d02f5a5ec58',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Stromboli Live',
                'volcano' => 'Stromboli',
                'country' => 'Italy',
                'source' => 'INGV Catania',
                'stream_url' => 'https://www.ct.ingv.it/sezioniesterne/StreamingEolie.php',
                'embed_url' => 'https://garr.tv/videos/embed/8790a7a8-211c-4794-bcb2-41e24cd2e322',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Popocatepetl',
                'volcano' => 'Popocatepetl',
                'country' => 'Mexico',
                'source' => 'CENAPRED',
                'stream_url' => 'https://www.cenapred.gob.mx/es/reportesVolcanesMX/',
                'embed_url' => 'http://www.atlasnacionalderiesgos.gob.mx/app/BoletinPopo/sync3.html',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Fuego',
                'volcano' => 'Fuego',
                'country' => 'Guatemala',
                'source' => 'Michigan Tech (with INSIVUMEH support)',
                'stream_url' => 'https://ovfuego-norte.geo.mtu.edu/animations.php',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea KWcam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/KWcam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/V1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V2cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/V2cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V3cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/V3cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea B1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/B1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea F1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/F1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea K2cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/K2cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea KPcam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/KPcam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mauna Loa Webcams',
                'volcano' => 'Mauna Loa',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mauna-loa/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mauna Loa M1cam',
                'volcano' => 'Mauna Loa',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mauna-loa/webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/M1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mauna Loa M2cam',
                'volcano' => 'Mauna Loa',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mauna-loa/webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/M2cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mount St. Helens Webcams',
                'volcano' => 'Mount St. Helens',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mount-st-helens/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mount Rainier Volcano Webcams',
                'volcano' => 'Mount Rainier',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mount-rainier/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mount Hood Volcano Webcams',
                'volcano' => 'Mount Hood',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mount-hood/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mount Adams Volcano Webcams',
                'volcano' => 'Mount Adams',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mount-adams/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Mount Baker Volcano Webcams',
                'volcano' => 'Mount Baker',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/mount-baker/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Three Sisters Volcano Webcams',
                'volcano' => 'Three Sisters',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/three-sisters/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Newberry Volcano Webcams',
                'volcano' => 'Newberry',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/newberry/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Crater Lake Webcams',
                'volcano' => 'Crater Lake',
                'country' => 'United States',
                'source' => 'USGS CVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/crater-lake/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Shishaldin Webcams',
                'volcano' => 'Shishaldin',
                'country' => 'United States',
                'source' => 'USGS AVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/shishaldin/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Pavlof Webcams',
                'volcano' => 'Pavlof',
                'country' => 'United States',
                'source' => 'USGS AVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/pavlof/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Great Sitkin Webcams',
                'volcano' => 'Great Sitkin',
                'country' => 'United States',
                'source' => 'USGS AVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/great-sitkin/webcams',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Semeru Camera',
                'volcano' => 'Semeru',
                'country' => 'Indonesia',
                'source' => 'Magma Indonesia',
                'stream_url' => 'https://magma.esdm.go.id/v1/gunung-api/laporan-harian',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Merapi Camera',
                'volcano' => 'Merapi',
                'country' => 'Indonesia',
                'source' => 'Magma Indonesia',
                'stream_url' => 'https://magma.esdm.go.id/v1/gunung-api/laporan-harian',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Sakurajima Camera',
                'volcano' => 'Sakurajima',
                'country' => 'Japan',
                'source' => 'Kagoshima Prefecture',
                'stream_url' => 'https://www.kagoshima-yokanavi.jp/en/feature/sakurajima-livecamera',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Reykjanes Peninsula Live Cams',
                'volcano' => 'Reykjanes',
                'country' => 'Iceland',
                'source' => 'Live From Iceland',
                'stream_url' => 'https://www.livefromiceland.is/webcams/reykjanes/',
                'status' => 'Monitoring',
            ],
        ],
    ],
    'earthquake_cams' => [
        'provider' => 'Curated Seismic Region Cameras',
        'items' => [
            [
                'name' => 'San Francisco Bay Live Cam',
                'region' => 'San Andreas Fault Corridor',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/california/sanfrancisco/?cam=sfskyline',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'status' => 'Urban seismic watch',
            ],
            [
                'name' => 'Los Angeles Basin Live Cam',
                'region' => 'Southern California Fault System',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/california/losangeles/hollywood/',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'status' => 'Urban seismic watch',
            ],
            [
                'name' => 'Anchorage Live Cam',
                'region' => 'Alaska Subduction Zone',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Anchorage/webcams/1268955080',
                'latitude' => 61.2181,
                'longitude' => -149.9003,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Tokyo Bay Live Cam',
                'region' => 'Japan Trench Interface',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Tokyo/Tokyo-Bay/webcams/1462813288',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'status' => 'Megathrust watch',
            ],
            [
                'name' => 'Sendai Coast Live Cam',
                'region' => 'Tohoku Offshore',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Miyagi/Sendai/webcams/1460736154',
                'latitude' => 38.2682,
                'longitude' => 140.8694,
                'status' => 'Megathrust watch',
            ],
            [
                'name' => 'Taipei Live Cam',
                'region' => 'Ryukyu Seismic Arc',
                'country' => 'Taiwan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Taiwan/Taipei/Taipei/webcams/1583403437',
                'latitude' => 25.0330,
                'longitude' => 121.5654,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Manila Bay Live Cam',
                'region' => 'Philippine Mobile Belt',
                'country' => 'Philippines',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Philippines/Metro-Manila/Manila/webcams/1460983534',
                'latitude' => 14.5995,
                'longitude' => 120.9842,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Santiago Live Cam',
                'region' => 'Chile Subduction Margin',
                'country' => 'Chile',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Chile/Metropolitana-de-Santiago/Santiago/webcams/1308731660',
                'latitude' => -33.4489,
                'longitude' => -70.6693,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Quito Live Cam',
                'region' => 'Northern Andes Seismic Belt',
                'country' => 'Ecuador',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Ecuador/Pichincha/Quito/webcams/1464445909',
                'latitude' => -0.1807,
                'longitude' => -78.4678,
                'status' => 'Andean seismic watch',
            ],
            [
                'name' => 'Mexico City Live Cam',
                'region' => 'Trans-Mexican Seismic Zone',
                'country' => 'Mexico',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/world/mexico/mexicocity/',
                'latitude' => 19.4326,
                'longitude' => -99.1332,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Istanbul Bosphorus Live Cam',
                'region' => 'North Anatolian Fault',
                'country' => 'Turkey',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/T%C3%BCrkiye/Istanbul/Istanbul/webcams/1462953896',
                'latitude' => 41.0082,
                'longitude' => 28.9784,
                'status' => 'Strike-slip watch',
            ],
            [
                'name' => 'Athens Live Cam',
                'region' => 'Hellenic Arc',
                'country' => 'Greece',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Greece/Attica/Athens/webcams/1463007280',
                'latitude' => 37.9838,
                'longitude' => 23.7275,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Reykjavik Harbor Live Cam',
                'region' => 'Iceland Seismic Rift Zone',
                'country' => 'Iceland',
                'source' => 'Live From Iceland',
                'stream_url' => 'https://www.livefromiceland.is/webcams/reykjavik/',
                'latitude' => 64.1466,
                'longitude' => -21.9426,
                'status' => 'Rift seismic watch',
            ],
            [
                'name' => 'Wellington Live Cam',
                'region' => 'New Zealand Plate Boundary',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Wellington/Wellington/webcams/1321301029',
                'latitude' => -41.2866,
                'longitude' => 174.7756,
                'status' => 'Plate-boundary watch',
            ],
            [
                'name' => 'Seattle Waterfront Live Cam',
                'region' => 'Cascadia Subduction Margin',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/washington/seattle/',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Portland Downtown Live Cam',
                'region' => 'Cascadia Forearc',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Oregon/Portland/webcams/1268874680',
                'latitude' => 45.5152,
                'longitude' => -122.6784,
                'status' => 'Forearc seismic watch',
            ],
            [
                'name' => 'Vancouver Harbor Live Cam',
                'region' => 'Cascadia North Segment',
                'country' => 'Canada',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Canada/British-Columbia/Vancouver/webcams/1258986533',
                'latitude' => 49.2827,
                'longitude' => -123.1207,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Lima Coast Live Cam',
                'region' => 'Peru Subduction Margin',
                'country' => 'Peru',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Peru/Lima/Lima/webcams/1261532318',
                'latitude' => -12.0464,
                'longitude' => -77.0428,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Bogota Live Cam',
                'region' => 'Northern Andes Seismic Corridor',
                'country' => 'Colombia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Colombia/Bogota/Bogot%C3%A1/webcams/1458573504',
                'latitude' => 4.7110,
                'longitude' => -74.0721,
                'status' => 'Andean seismic watch',
            ],
            [
                'name' => 'Catania Coast Live Cam',
                'region' => 'Sicily Seismic Belt',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Sicily/Catania/webcams/1268909800',
                'latitude' => 37.5079,
                'longitude' => 15.0830,
                'status' => 'Mediterranean seismic watch',
            ],
            [
                'name' => 'Naples Gulf Live Cam',
                'region' => 'Campania Seismic Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Campania/Naples/webcams/1268910024',
                'latitude' => 40.8518,
                'longitude' => 14.2681,
                'status' => 'Mediterranean seismic watch',
            ],
            [
                'name' => 'Marrakesh Live Cam',
                'region' => 'Atlas Seismic Front',
                'country' => 'Morocco',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Morocco/Marrakesh-Safi/Marrakesh/webcams/1602861223',
                'latitude' => 31.6295,
                'longitude' => -7.9811,
                'status' => 'Intraplate seismic watch',
            ],
            [
                'name' => 'Jakarta Live Cam',
                'region' => 'Sunda Arc Seismic Zone',
                'country' => 'Indonesia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Indonesia/Jakarta/Jakarta/webcams/1460836413',
                'latitude' => -6.2088,
                'longitude' => 106.8456,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Christchurch Live Cam',
                'region' => 'Alpine Fault Influence Zone',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Canterbury/Christchurch/webcams/1321301065',
                'latitude' => -43.5321,
                'longitude' => 172.6362,
                'status' => 'Plate-boundary watch',
            ],
            [
                'name' => 'San Diego Coast Live Cam',
                'region' => 'Southern San Andreas-Salton System',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/california/sandiego/',
                'latitude' => 32.7157,
                'longitude' => -117.1611,
                'status' => 'Urban seismic watch',
            ],
            [
                'name' => 'Sacramento Valley Live Cam',
                'region' => 'Northern California Interior Faults',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/California/Sacramento/webcams/1268876880',
                'latitude' => 38.5816,
                'longitude' => -121.4944,
                'status' => 'Regional seismic watch',
            ],
            [
                'name' => 'Kodiak Harbor Live Cam',
                'region' => 'Alaska-Aleutian Subduction Front',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Kodiak/webcams/1268954862',
                'latitude' => 57.7900,
                'longitude' => -152.4072,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Seward Bay Live Cam',
                'region' => 'Kenai Subduction Margin',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Seward/webcams/1268955101',
                'latitude' => 60.1042,
                'longitude' => -149.4422,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Izmir Bay Live Cam',
                'region' => 'Aegean Extensional Zone',
                'country' => 'Turkey',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/T%C3%BCrkiye/%C4%B0zmir/%C4%B0zmir/webcams/1462953964',
                'latitude' => 38.4237,
                'longitude' => 27.1428,
                'status' => 'Aegean seismic watch',
            ],
            [
                'name' => 'Patras Gulf Live Cam',
                'region' => 'Western Hellenic Arc',
                'country' => 'Greece',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Greece/Western-Greece/Patras/webcams/1463007088',
                'latitude' => 38.2466,
                'longitude' => 21.7346,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Lisbon Coast Live Cam',
                'region' => 'SW Iberia Seismic Margin',
                'country' => 'Portugal',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Portugal/Lisbon-District/Lisbon/webcams/1310889152',
                'latitude' => 38.7223,
                'longitude' => -9.1393,
                'status' => 'Atlantic margin watch',
            ],
            [
                'name' => 'San Juan Live Cam',
                'region' => 'Puerto Rico Trench Margin',
                'country' => 'Puerto Rico',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/world/puertorico/sanjuan/',
                'latitude' => 18.4655,
                'longitude' => -66.1057,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Guayaquil Live Cam',
                'region' => 'Ecuador Coastal Subduction Zone',
                'country' => 'Ecuador',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Ecuador/Guayas/Guayaquil/webcams/1464446011',
                'latitude' => -2.1709,
                'longitude' => -79.9224,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Valparaiso Bay Live Cam',
                'region' => 'Central Chile Subduction Margin',
                'country' => 'Chile',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Chile/Valpara%C3%ADso/Valpara%C3%ADso/webcams/1308731602',
                'latitude' => -33.0472,
                'longitude' => -71.6127,
                'status' => 'Subduction watch',
            ],
            [
                'name' => 'Kobe Harbor Live Cam',
                'region' => 'SW Japan Active Fault Corridor',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Hyogo/Kobe/webcams/1460736082',
                'latitude' => 34.6901,
                'longitude' => 135.1955,
                'status' => 'Active-fault watch',
            ],
            [
                'name' => 'Surabaya Coast Live Cam',
                'region' => 'Java Trench Forearc',
                'country' => 'Indonesia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Indonesia/East-Java/Surabaya/webcams/1460836764',
                'latitude' => -7.2575,
                'longitude' => 112.7521,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'L Aquila Live Cam',
                'region' => 'Central Apennine Seismic Belt',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Abruzzo/L-Aquila/webcams/1268909951',
                'latitude' => 42.3498,
                'longitude' => 13.3995,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Amatrice Area Live Cam',
                'region' => 'Central Apennine Fault System',
                'country' => 'Italy',
                'source' => 'Meteo Appennino',
                'stream_url' => 'https://www.meteoappennino.it/webcam/amatrice',
                'latitude' => 42.6276,
                'longitude' => 13.2931,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Norcia Live Cam',
                'region' => 'Umbro-Marchigiano Apennines',
                'country' => 'Italy',
                'source' => 'Umbria Webcam',
                'stream_url' => 'https://www.umbriameteo.com/webcam/norcia',
                'latitude' => 42.7924,
                'longitude' => 13.0922,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Camerino Live Cam',
                'region' => 'Marche Apennine Seismic Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Marche/Camerino/webcams/1268910363',
                'latitude' => 43.1365,
                'longitude' => 13.0681,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Perugia Live Cam',
                'region' => 'Umbria Seismic District',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Umbria/Perugia/webcams/1268910104',
                'latitude' => 43.1107,
                'longitude' => 12.3908,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Rieti Live Cam',
                'region' => 'Lazio-Apennine Transition',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Lazio/Rieti/webcams/1268910131',
                'latitude' => 42.4048,
                'longitude' => 12.8567,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Teramo Live Cam',
                'region' => 'Abruzzo Apennine Foothills',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Abruzzo/Teramo/webcams/1268909943',
                'latitude' => 42.6589,
                'longitude' => 13.7044,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Ancona Coast Live Cam',
                'region' => 'Adriatic-Central Italy Seismic Margin',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Marche/Ancona/webcams/1268910341',
                'latitude' => 43.6158,
                'longitude' => 13.5189,
                'status' => 'Adriatic seismic watch',
            ],
            [
                'name' => 'Pescara Coast Live Cam',
                'region' => 'Adriatic Foreland',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Abruzzo/Pescara/webcams/1268909931',
                'latitude' => 42.4618,
                'longitude' => 14.2161,
                'status' => 'Adriatic seismic watch',
            ],
            [
                'name' => 'Campobasso Live Cam',
                'region' => 'Southern Apennine Arc',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Molise/Campobasso/webcams/1268910380',
                'latitude' => 41.5600,
                'longitude' => 14.6627,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Potenza Live Cam',
                'region' => 'Lucanian Apennines',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Basilicata/Potenza/webcams/1268910414',
                'latitude' => 40.6401,
                'longitude' => 15.8057,
                'status' => 'Apennine seismic watch',
            ],
            [
                'name' => 'Bologna Hills Live Cam',
                'region' => 'Northern Apennine Front',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Emilia-Romagna/Bologna/webcams/1268910451',
                'latitude' => 44.4949,
                'longitude' => 11.3426,
                'status' => 'Apennine front watch',
            ],
            [
                'name' => 'Rome Hills Live Cam',
                'region' => 'Central Italy Fault Transition',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Lazio/Rome/webcams/1268910138',
                'latitude' => 41.9028,
                'longitude' => 12.4964,
                'status' => 'Apennine transition watch',
            ],
            [
                'name' => 'Florence Ridge Live Cam',
                'region' => 'Northern Apennine Fault Belt',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Tuscany/Florence/webcams/1268910152',
                'latitude' => 43.7696,
                'longitude' => 11.2558,
                'status' => 'Apennine front watch',
            ],
            [
                'name' => 'Hilo Bay Live Cam',
                'region' => 'Hawaii Seismic-Volcanic Zone',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Hawaii/Hilo/webcams/1268955331',
                'latitude' => 19.7070,
                'longitude' => -155.0885,
                'status' => 'Island seismic watch',
            ],
            [
                'name' => 'Honolulu Coast Live Cam',
                'region' => 'Central Pacific Seismic Context',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/hawaii/oahu/waikiki/',
                'latitude' => 21.3069,
                'longitude' => -157.8583,
                'status' => 'Pacific seismic watch',
            ],
            [
                'name' => 'Osaka Bay Live Cam',
                'region' => 'Nankai Trough Forearc',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Osaka/Osaka/webcams/1460736025',
                'latitude' => 34.6937,
                'longitude' => 135.5023,
                'status' => 'Megathrust watch',
            ],
            [
                'name' => 'Fukuoka Harbor Live Cam',
                'region' => 'SW Japan Active Margin',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Fukuoka/Fukuoka/webcams/1460736001',
                'latitude' => 33.5902,
                'longitude' => 130.4017,
                'status' => 'Active-margin watch',
            ],
            [
                'name' => 'Kathmandu Valley Live Cam',
                'region' => 'Himalayan Collision Front',
                'country' => 'Nepal',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Nepal/Central-Region/Kathmandu/webcams/1464480216',
                'latitude' => 27.7172,
                'longitude' => 85.3240,
                'status' => 'Collision-zone watch',
            ],
            [
                'name' => 'Tehran Skyline Live Cam',
                'region' => 'Alborz Active Fault System',
                'country' => 'Iran',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Iran/Tehran/Tehran/webcams/1464473033',
                'latitude' => 35.6892,
                'longitude' => 51.3890,
                'status' => 'Active-fault watch',
            ],
            [
                'name' => 'Tbilisi Live Cam',
                'region' => 'Greater Caucasus Seismic Belt',
                'country' => 'Georgia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Georgia/Tbilisi/Tbilisi/webcams/1456850411',
                'latitude' => 41.7151,
                'longitude' => 44.8271,
                'status' => 'Caucasus seismic watch',
            ],
            [
                'name' => 'Yerevan Live Cam',
                'region' => 'Lesser Caucasus Seismic Belt',
                'country' => 'Armenia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Armenia/Yerevan/Yerevan/webcams/1456849564',
                'latitude' => 40.1792,
                'longitude' => 44.4991,
                'status' => 'Caucasus seismic watch',
            ],
            [
                'name' => 'Bucharest Live Cam',
                'region' => 'Vrancea Deep Seismic Source',
                'country' => 'Romania',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Romania/Bucharest/Bucharest/webcams/1310969506',
                'latitude' => 44.4268,
                'longitude' => 26.1025,
                'status' => 'Vrancea watch',
            ],
            [
                'name' => 'Skopje Live Cam',
                'region' => 'Balkan Seismic Corridor',
                'country' => 'North Macedonia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/North-Macedonia/Skopje/Skopje/webcams/1464479592',
                'latitude' => 41.9981,
                'longitude' => 21.4254,
                'status' => 'Balkan seismic watch',
            ],
            [
                'name' => 'San Salvador Live Cam',
                'region' => 'Central America Volcanic Arc',
                'country' => 'El Salvador',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/El-Salvador/San-Salvador/San-Salvador/webcams/1464457950',
                'latitude' => 13.6929,
                'longitude' => -89.2182,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'Guatemala City Live Cam',
                'region' => 'Central America Subduction-Arc Zone',
                'country' => 'Guatemala',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Guatemala/Guatemala/Guatemala-City/webcams/1464460781',
                'latitude' => 14.6349,
                'longitude' => -90.5069,
                'status' => 'Arc seismic watch',
            ],
            [
                'name' => 'La Paz Live Cam',
                'region' => 'Central Andes Seismic Belt',
                'country' => 'Bolivia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Bolivia/La-Paz/La-Paz/webcams/1458579860',
                'latitude' => -16.4897,
                'longitude' => -68.1193,
                'status' => 'Andean seismic watch',
            ],
        ],
    ],
    'weather_cams' => [
        'provider' => 'Curated Severe Weather Cameras',
        'items' => [
            [
                'name' => 'Miami Beach Storm Cam',
                'region' => 'Florida Atlantic Coast',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/florida/miamiandthebeaches/',
                'status' => 'Hurricane and surge watch',
                'risk_tier' => 4,
                'region_tags' => ['florida', 'miami', 'atlantic', 'hurricane'],
            ],
            [
                'name' => 'Key West Harbor Cam',
                'region' => 'Florida Keys',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Florida/Key-West/webcams/1268959052',
                'status' => 'Tropical cyclone watch',
                'risk_tier' => 4,
                'region_tags' => ['florida', 'keys', 'key west', 'hurricane'],
            ],
            [
                'name' => 'New Orleans River Cam',
                'region' => 'Louisiana Gulf Coast',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/louisiana/neworleans/?cam=bourbonstreet',
                'status' => 'Hurricane and flood watch',
                'risk_tier' => 4,
                'region_tags' => ['louisiana', 'new orleans', 'gulf', 'flood'],
            ],
            [
                'name' => 'Houston Bay Storm Cam',
                'region' => 'Texas Gulf Coast',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Texas/Houston/webcams/1268872761',
                'status' => 'Gulf severe weather watch',
                'risk_tier' => 4,
                'region_tags' => ['texas', 'houston', 'gulf', 'hurricane', 'flood'],
            ],
            [
                'name' => 'Tampa Bay Cam',
                'region' => 'Florida Gulf Coast',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Florida/Tampa/webcams/1268959021',
                'status' => 'Hurricane and storm surge watch',
                'risk_tier' => 4,
                'region_tags' => ['florida', 'tampa', 'gulf', 'hurricane'],
            ],
            [
                'name' => 'Oklahoma City Sky Cam',
                'region' => 'Central Tornado Alley',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Oklahoma/Oklahoma-City/webcams/1268872463',
                'status' => 'Tornado watch',
                'risk_tier' => 4,
                'region_tags' => ['oklahoma', 'oklahoma city', 'tornado', 'thunderstorm'],
            ],
            [
                'name' => 'Wichita Sky Cam',
                'region' => 'Kansas Tornado Corridor',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Kansas/Wichita/webcams/1268872408',
                'status' => 'Tornado and hail watch',
                'risk_tier' => 4,
                'region_tags' => ['kansas', 'wichita', 'tornado', 'hail'],
            ],
            [
                'name' => 'Denver Front Range Cam',
                'region' => 'Rockies Severe Storm Zone',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/colorado/denver/',
                'status' => 'Severe thunderstorm watch',
                'risk_tier' => 3,
                'region_tags' => ['colorado', 'denver', 'storm', 'hail'],
            ],
            [
                'name' => 'Phoenix Heat Cam',
                'region' => 'Southwest Heat Risk Zone',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Arizona/Phoenix/webcams/1268872037',
                'status' => 'Extreme heat watch',
                'risk_tier' => 3,
                'region_tags' => ['arizona', 'phoenix', 'heat'],
            ],
            [
                'name' => 'Los Angeles Basin Sky Cam',
                'region' => 'Southern California',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/california/losangeles/hollywood/',
                'status' => 'Urban severe weather watch',
                'risk_tier' => 2,
                'region_tags' => ['california', 'los angeles', 'storm'],
            ],
            [
                'name' => 'London River Cam',
                'region' => 'UK Flood and Wind Risk Zone',
                'country' => 'United Kingdom',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/world/england/london/',
                'status' => 'Wind and flood watch',
                'risk_tier' => 2,
                'region_tags' => ['uk', 'united kingdom', 'london', 'flood', 'wind'],
            ],
            [
                'name' => 'Amsterdam Canal Cam',
                'region' => 'Lowlands Flood Context',
                'country' => 'Netherlands',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Netherlands/North-Holland/Amsterdam/webcams/1305587048',
                'status' => 'Flood and wind watch',
                'risk_tier' => 2,
                'region_tags' => ['netherlands', 'amsterdam', 'flood', 'wind'],
            ],
            [
                'name' => 'Lisbon Atlantic Cam',
                'region' => 'Portugal Atlantic Coast',
                'country' => 'Portugal',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Portugal/Lisbon-District/Lisbon/webcams/1310889152',
                'status' => 'Atlantic storm watch',
                'risk_tier' => 2,
                'region_tags' => ['portugal', 'lisbon', 'atlantic', 'storm'],
            ],
            [
                'name' => 'Athens Metro Cam',
                'region' => 'Eastern Mediterranean',
                'country' => 'Greece',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Greece/Attica/Athens/webcams/1463007280',
                'status' => 'Mediterranean storm watch',
                'risk_tier' => 2,
                'region_tags' => ['greece', 'athens', 'storm', 'mediterranean'],
            ],
            [
                'name' => 'Istanbul Bosphorus Cam',
                'region' => 'Black Sea Gateway',
                'country' => 'Turkey',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/T%C3%BCrkiye/Istanbul/Istanbul/webcams/1462953896',
                'status' => 'Wind and storm watch',
                'risk_tier' => 2,
                'region_tags' => ['turkey', 'istanbul', 'wind', 'storm'],
            ],
            [
                'name' => 'Tokyo Bay Weather Cam',
                'region' => 'Japan Typhoon Exposure',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Tokyo/Tokyo-Bay/webcams/1462813288',
                'status' => 'Typhoon watch',
                'risk_tier' => 4,
                'region_tags' => ['japan', 'tokyo', 'typhoon', 'storm'],
            ],
            [
                'name' => 'Osaka Bay Weather Cam',
                'region' => 'Japan Pacific Side',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Osaka/Osaka/webcams/1460736025',
                'status' => 'Typhoon watch',
                'risk_tier' => 3,
                'region_tags' => ['japan', 'osaka', 'typhoon', 'storm'],
            ],
            [
                'name' => 'Manila Bay Weather Cam',
                'region' => 'Philippines Typhoon Belt',
                'country' => 'Philippines',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Philippines/Metro-Manila/Manila/webcams/1460983534',
                'status' => 'Typhoon watch',
                'risk_tier' => 4,
                'region_tags' => ['philippines', 'manila', 'typhoon', 'storm', 'flood'],
            ],
            [
                'name' => 'Jakarta Monsoon Cam',
                'region' => 'Indonesia Monsoon Belt',
                'country' => 'Indonesia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Indonesia/Jakarta/Jakarta/webcams/1460836413',
                'status' => 'Monsoon flood watch',
                'risk_tier' => 3,
                'region_tags' => ['indonesia', 'jakarta', 'monsoon', 'flood', 'storm'],
            ],
            [
                'name' => 'Bangkok River Cam',
                'region' => 'Chao Phraya Flood Zone',
                'country' => 'Thailand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Thailand/Bangkok/Bangkok/webcams/1464477374',
                'status' => 'Flood watch',
                'risk_tier' => 3,
                'region_tags' => ['thailand', 'bangkok', 'flood', 'storm'],
            ],
            [
                'name' => 'Sydney Harbor Weather Cam',
                'region' => 'SE Australia Coast',
                'country' => 'Australia',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/world/australia/sydney/',
                'status' => 'Coastal storm watch',
                'risk_tier' => 2,
                'region_tags' => ['australia', 'sydney', 'storm'],
            ],
            [
                'name' => 'Auckland Harbor Weather Cam',
                'region' => 'New Zealand North Island',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Auckland/Auckland/webcams/1321300947',
                'status' => 'Storm and wind watch',
                'risk_tier' => 2,
                'region_tags' => ['new zealand', 'auckland', 'storm', 'wind'],
            ],
            [
                'name' => 'Cape Town Atlantic Cam',
                'region' => 'South Africa Cape Zone',
                'country' => 'South Africa',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/South-Africa/Western-Cape/Cape-Town/webcams/1326687575',
                'status' => 'Wind and storm watch',
                'risk_tier' => 2,
                'region_tags' => ['south africa', 'cape town', 'wind', 'storm'],
            ],
            [
                'name' => 'Rio Coast Weather Cam',
                'region' => 'SE Brazil Coastal Storm Zone',
                'country' => 'Brazil',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Brazil/Rio-de-Janeiro/Rio-de-Janeiro/webcams/1296507913',
                'status' => 'Storm and flood watch',
                'risk_tier' => 2,
                'region_tags' => ['brazil', 'rio', 'storm', 'flood'],
            ],
            [
                'name' => 'Milan Sky Cam',
                'region' => 'North Italy Severe Storm Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Lombardy/Milan/webcams/1268910187',
                'status' => 'Thunderstorm and hail watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'milan', 'storm', 'hail'],
            ],
            [
                'name' => 'Venice Lagoon Cam',
                'region' => 'North Adriatic Flood Risk',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/veneto/venezia/bacino-san-marco-riva-degli-schiavoni.html',
                'status' => 'Flood and storm surge watch',
                'risk_tier' => 3,
                'region_tags' => ['italy', 'venice', 'venezia', 'flood', 'storm'],
            ],
            [
                'name' => 'Genoa Harbor Weather Cam',
                'region' => 'Ligurian Storm Corridor',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Liguria/Genoa/webcams/1268910171',
                'status' => 'Storm and heavy rain watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'genoa', 'liguria', 'storm', 'flood'],
            ],
            [
                'name' => 'Rome Weather Cam',
                'region' => 'Central Italy Storm Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Lazio/Rome/webcams/1268910138',
                'status' => 'Thunderstorm watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'rome', 'storm'],
            ],
            [
                'name' => 'Naples Gulf Weather Cam',
                'region' => 'South Italy Coastal Storm Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Campania/Naples/webcams/1268910024',
                'status' => 'Coastal storm watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'naples', 'campania', 'storm'],
            ],
            [
                'name' => 'Palermo Coast Cam',
                'region' => 'Sicily Coastal Weather Zone',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Sicily/Palermo/webcams/1268909826',
                'status' => 'Mediterranean storm watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'sicily', 'palermo', 'storm'],
            ],
        ],
    ],
    'space_weather_cams' => [
        'provider' => 'Curated Aurora & Space Weather Cameras',
        'items' => [
            [
                'name' => 'Tromso Sky Cam',
                'region' => 'Norway Arctic Aurora Belt',
                'country' => 'Norway',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Norway/Troms-og-Finnmark/Tromso/webcams/1324852755',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['tromso', 'norway', 'norvegia'],
            ],
            [
                'name' => 'Svalbard Longyearbyen Cam',
                'region' => 'Svalbard High Arctic',
                'country' => 'Svalbard',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Svalbard/Longyearbyen/Longyearbyen/webcams/1322234022',
                'status' => 'High-latitude sky watch',
                'risk_tier' => 4,
                'region_tags' => ['longyearbyen', 'svalbard'],
            ],
            [
                'name' => 'Kiruna Aurora Cam',
                'region' => 'Swedish Lapland',
                'country' => 'Sweden',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Sweden/Norrbotten/Kiruna/webcams/1321265215',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['kiruna', 'sweden', 'svezia'],
            ],
            [
                'name' => 'Abisko Sky Station Cam',
                'region' => 'Swedish Lapland',
                'country' => 'Sweden',
                'source' => 'Aurora Sky Station',
                'stream_url' => 'https://www.swedishlapland.com/stories/abisko-aurora-sky-station/',
                'status' => 'All-sky aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['abisko', 'sweden', 'svezia'],
            ],
            [
                'name' => 'Rovaniemi Sky Cam',
                'region' => 'Finnish Lapland',
                'country' => 'Finland',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Finland/Lapland/Rovaniemi/webcams/1326952928',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['rovaniemi', 'finland', 'finlandia'],
            ],
            [
                'name' => 'Sodankyla All Sky',
                'region' => 'Finnish Lapland',
                'country' => 'Finland',
                'source' => 'Sodankyla Geophysical Observatory',
                'stream_url' => 'https://www.sgo.fi/Data/RealTime/AllSkyData/',
                'status' => 'Geomagnetic sky watch',
                'risk_tier' => 4,
                'region_tags' => ['sodankyla', 'finland', 'finlandia'],
            ],
            [
                'name' => 'Reykjavik Harbor Cam',
                'region' => 'Iceland Atlantic-Nordic Gateway',
                'country' => 'Iceland',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Iceland/Capital-Region/Reykjavik/webcams/1321479852',
                'status' => 'Aurora and cloud-gap watch',
                'risk_tier' => 4,
                'region_tags' => ['reykjavik', 'iceland', 'islanda'],
            ],
            [
                'name' => 'Akureyri Sky Cam',
                'region' => 'North Iceland',
                'country' => 'Iceland',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Iceland/Northeastern-Region/Akureyri/webcams/1321479899',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['akureyri', 'iceland', 'islanda'],
            ],
            [
                'name' => 'Nuuk Fjord Cam',
                'region' => 'West Greenland',
                'country' => 'Greenland',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Greenland/Sermersooq/Nuuk/webcams/1321480467',
                'status' => 'Polar sky watch',
                'risk_tier' => 4,
                'region_tags' => ['nuuk', 'greenland', 'groenlandia'],
            ],
            [
                'name' => 'Torshavn Port Cam',
                'region' => 'Faroe Islands',
                'country' => 'Faroe Islands',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Faroe-Islands/Torshavn/Torshavn/webcams/1321479361',
                'status' => 'North Atlantic sky watch',
                'risk_tier' => 3,
                'region_tags' => ['torshavn', 'faroe'],
            ],
            [
                'name' => 'Fairbanks Aurora Cam',
                'region' => 'Alaska Interior',
                'country' => 'United States',
                'source' => 'Explore.org',
                'stream_url' => 'https://explore.org/livecams/aurora-borealis/northern-lights-cam',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['fairbanks', 'alaska', 'stati uniti', 'united states'],
            ],
            [
                'name' => 'Anchorage Skyline Cam',
                'region' => 'Southcentral Alaska',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Anchorage/webcams/1268954701',
                'status' => 'Geomagnetic sky watch',
                'risk_tier' => 3,
                'region_tags' => ['anchorage', 'alaska', 'stati uniti', 'united states'],
            ],
            [
                'name' => 'Yellowknife Aurora Village Cam',
                'region' => 'Northwest Territories',
                'country' => 'Canada',
                'source' => 'Aurora Village',
                'stream_url' => 'https://www.auroravillage.com/live-aurora-cam/',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['yellowknife', 'canada'],
            ],
            [
                'name' => 'Whitehorse Sky Cam',
                'region' => 'Yukon',
                'country' => 'Canada',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Canada/Yukon/Whitehorse/webcams/1319342828',
                'status' => 'Aurora watch',
                'risk_tier' => 4,
                'region_tags' => ['whitehorse', 'canada'],
            ],
            [
                'name' => 'Iqaluit Harbor Cam',
                'region' => 'Nunavut',
                'country' => 'Canada',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Canada/Nunavut/Iqaluit/webcams/1321318804',
                'status' => 'Polar sky watch',
                'risk_tier' => 4,
                'region_tags' => ['iqaluit', 'canada'],
            ],
            [
                'name' => 'St Johns Night Sky Cam',
                'region' => 'Newfoundland',
                'country' => 'Canada',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Canada/Newfoundland-and-Labrador/St-John%27s/webcams/1287750545',
                'status' => 'Geomagnetic sky watch',
                'risk_tier' => 3,
                'region_tags' => ['st johns', 'canada'],
            ],
            [
                'name' => 'Edinburgh Skyline Cam',
                'region' => 'Northern UK',
                'country' => 'United Kingdom',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-Kingdom/Scotland/Edinburgh/webcams/1307335112',
                'status' => 'Aurora window watch',
                'risk_tier' => 3,
                'region_tags' => ['edinburgh', 'regno unito', 'united kingdom'],
            ],
            [
                'name' => 'Bergen Harbor Cam',
                'region' => 'Western Norway',
                'country' => 'Norway',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Norway/Vestland/Bergen/webcams/1307726004',
                'status' => 'Aurora window watch',
                'risk_tier' => 3,
                'region_tags' => ['bergen', 'norway', 'norvegia'],
            ],
            [
                'name' => 'Oslo Skyline Cam',
                'region' => 'Southern Norway',
                'country' => 'Norway',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Norway/Oslo/Oslo/webcams/1307725987',
                'status' => 'Geomagnetic sky watch',
                'risk_tier' => 2,
                'region_tags' => ['oslo', 'norway', 'norvegia'],
            ],
            [
                'name' => 'Aosta Valley Sky Cam',
                'region' => 'Italian Alps',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/valle-daosta/aosta/aosta-centro.html',
                'status' => 'Alpine sky watch',
                'risk_tier' => 2,
                'region_tags' => ['aosta', 'italy', 'italia'],
            ],
            [
                'name' => 'Livigno Alpine Cam',
                'region' => 'Italian Alps',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/lombardia/sondrio/livigno.html',
                'status' => 'Alpine sky watch',
                'risk_tier' => 2,
                'region_tags' => ['livigno', 'italy', 'italia'],
            ],
            [
                'name' => 'Cortina Dolomites Cam',
                'region' => 'Dolomites',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/veneto/belluno/cortina-d-ampezzo.html',
                'status' => 'Alpine night-sky watch',
                'risk_tier' => 2,
                'region_tags' => ['cortina', 'dolomites', 'italy', 'italia'],
            ],
            [
                'name' => 'Hokkaido All Sky Cam',
                'region' => 'North Japan',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Hokkaido/Sapporo/webcams/1462813260',
                'status' => 'High-latitude sky watch',
                'risk_tier' => 3,
                'region_tags' => ['sapporo', 'hokkaido', 'japan', 'giappone'],
            ],
            [
                'name' => 'Tasmania Night Sky Cam',
                'region' => 'Southern High Latitude',
                'country' => 'Australia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Australia/Tasmania/Hobart/webcams/1310934155',
                'status' => 'Southern aurora watch',
                'risk_tier' => 2,
                'region_tags' => ['hobart', 'tasmania', 'australia'],
            ],
            [
                'name' => 'Invercargill Sky Cam',
                'region' => 'South New Zealand',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Southland/Invercargill/webcams/1321301470',
                'status' => 'Southern aurora watch',
                'risk_tier' => 2,
                'region_tags' => ['invercargill', 'new zealand', 'nuova zelanda'],
            ],
        ],
    ],
    'tsunami_cams' => [
        'provider' => 'Curated Coastal Tsunami Watch Cameras',
        'items' => [
            [
                'name' => 'Hilo Bay Tsunami Cam',
                'region' => 'Hawaii Pacific Coast',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Hawaii/Hilo/webcams/1268955331',
                'latitude' => 19.7070,
                'longitude' => -155.0885,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['hawaii', 'hilo', 'pacific'],
            ],
            [
                'name' => 'Honolulu Waikiki Cam',
                'region' => 'Oahu Pacific Coast',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/hawaii/oahu/waikiki/',
                'latitude' => 21.2767,
                'longitude' => -157.8294,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['hawaii', 'honolulu', 'oahu', 'pacific'],
            ],
            [
                'name' => 'Kodiak Harbor Cam',
                'region' => 'Alaska Pacific Margin',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Kodiak/webcams/1268954862',
                'latitude' => 57.7900,
                'longitude' => -152.4072,
                'status' => 'Subduction coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['alaska', 'kodiak', 'aleutian', 'pacific'],
            ],
            [
                'name' => 'Seward Bay Cam',
                'region' => 'Gulf of Alaska',
                'country' => 'United States',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/United-States/Alaska/Seward/webcams/1268955101',
                'latitude' => 60.1042,
                'longitude' => -149.4422,
                'status' => 'Subduction coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['alaska', 'gulf', 'seward', 'pacific'],
            ],
            [
                'name' => 'San Diego Coast Cam',
                'region' => 'California Pacific Coast',
                'country' => 'United States',
                'source' => 'EarthCam',
                'stream_url' => 'https://www.earthcam.com/usa/california/sandiego/',
                'latitude' => 32.7157,
                'longitude' => -117.1611,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['california', 'san diego', 'pacific'],
            ],
            [
                'name' => 'Vancouver Harbor Cam',
                'region' => 'British Columbia Coast',
                'country' => 'Canada',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Canada/British-Columbia/Vancouver/webcams/1258986533',
                'latitude' => 49.2827,
                'longitude' => -123.1207,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['canada', 'british columbia', 'vancouver', 'pacific'],
            ],
            [
                'name' => 'Lima Coast Cam',
                'region' => 'Peru Subduction Coast',
                'country' => 'Peru',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Peru/Lima/Lima/webcams/1261532318',
                'latitude' => -12.0464,
                'longitude' => -77.0428,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['peru', 'lima', 'pacific'],
            ],
            [
                'name' => 'Valparaiso Bay Cam',
                'region' => 'Central Chile Coast',
                'country' => 'Chile',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Chile/Valpara%C3%ADso/Valpara%C3%ADso/webcams/1308731602',
                'latitude' => -33.0472,
                'longitude' => -71.6127,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['chile', 'valparaiso', 'pacific'],
            ],
            [
                'name' => 'Guayaquil Gulf Cam',
                'region' => 'Ecuador Pacific Coast',
                'country' => 'Ecuador',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Ecuador/Guayas/Guayaquil/webcams/1464446011',
                'latitude' => -2.1709,
                'longitude' => -79.9224,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['ecuador', 'guayaquil', 'pacific'],
            ],
            [
                'name' => 'Acapulco Bay Cam',
                'region' => 'Mexico Pacific Coast',
                'country' => 'Mexico',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Mexico/Guerrero/Acapulco/webcams/1290515379',
                'latitude' => 16.8531,
                'longitude' => -99.8237,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['mexico', 'acapulco', 'pacific'],
            ],
            [
                'name' => 'Puerto Vallarta Cam',
                'region' => 'West Mexico Coast',
                'country' => 'Mexico',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Mexico/Jalisco/Puerto-Vallarta/webcams/1290515454',
                'latitude' => 20.6534,
                'longitude' => -105.2253,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['mexico', 'jalisco', 'pacific'],
            ],
            [
                'name' => 'San Salvador Coast Cam',
                'region' => 'El Salvador Pacific Coast',
                'country' => 'El Salvador',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/El-Salvador/San-Salvador/San-Salvador/webcams/1464457950',
                'latitude' => 13.6929,
                'longitude' => -89.2182,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['el salvador', 'pacific'],
            ],
            [
                'name' => 'Guatemala Pacific Cam',
                'region' => 'Guatemala Pacific Coast',
                'country' => 'Guatemala',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Guatemala/Guatemala/Guatemala-City/webcams/1464460781',
                'latitude' => 14.6349,
                'longitude' => -90.5069,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['guatemala', 'pacific'],
            ],
            [
                'name' => 'Tokyo Bay Cam',
                'region' => 'East Japan Pacific Coast',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Tokyo/Tokyo-Bay/webcams/1462813288',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['japan', 'tokyo', 'pacific'],
            ],
            [
                'name' => 'Sendai Coast Cam',
                'region' => 'Tohoku Pacific Coast',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Miyagi/Sendai/webcams/1460736154',
                'latitude' => 38.2682,
                'longitude' => 140.8694,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['japan', 'sendai', 'miyagi', 'tohoku', 'pacific'],
            ],
            [
                'name' => 'Osaka Bay Cam',
                'region' => 'Nankai Coastal Zone',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Osaka/Osaka/webcams/1460736025',
                'latitude' => 34.6937,
                'longitude' => 135.5023,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['japan', 'osaka', 'nankai'],
            ],
            [
                'name' => 'Kobe Harbor Cam',
                'region' => 'SW Japan Coast',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Hyogo/Kobe/webcams/1460736082',
                'latitude' => 34.6901,
                'longitude' => 135.1955,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['japan', 'kobe', 'hyogo', 'nankai'],
            ],
            [
                'name' => 'Fukuoka Harbor Cam',
                'region' => 'Kyushu Coastal Zone',
                'country' => 'Japan',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Japan/Fukuoka/Fukuoka/webcams/1460736001',
                'latitude' => 33.5902,
                'longitude' => 130.4017,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['japan', 'fukuoka', 'kyushu'],
            ],
            [
                'name' => 'Manila Bay Cam',
                'region' => 'Philippine Coastal Belt',
                'country' => 'Philippines',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Philippines/Metro-Manila/Manila/webcams/1460983534',
                'latitude' => 14.5995,
                'longitude' => 120.9842,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['philippines', 'manila', 'pacific'],
            ],
            [
                'name' => 'Jakarta Bay Cam',
                'region' => 'Sunda Strait Context',
                'country' => 'Indonesia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Indonesia/Jakarta/Jakarta/webcams/1460836413',
                'latitude' => -6.2088,
                'longitude' => 106.8456,
                'status' => 'Indonesian coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['indonesia', 'jakarta', 'sunda'],
            ],
            [
                'name' => 'Surabaya Coast Cam',
                'region' => 'Java Sea Coastal Zone',
                'country' => 'Indonesia',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Indonesia/East-Java/Surabaya/webcams/1460836764',
                'latitude' => -7.2575,
                'longitude' => 112.7521,
                'status' => 'Indonesian coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['indonesia', 'surabaya', 'java'],
            ],
            [
                'name' => 'Wellington Harbor Cam',
                'region' => 'New Zealand Pacific Margin',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Wellington/Wellington/webcams/1321301029',
                'latitude' => -41.2866,
                'longitude' => 174.7756,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 4,
                'region_tags' => ['new zealand', 'wellington', 'pacific'],
            ],
            [
                'name' => 'Christchurch Coast Cam',
                'region' => 'South Island East Coast',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Canterbury/Christchurch/webcams/1321301065',
                'latitude' => -43.5321,
                'longitude' => 172.6362,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['new zealand', 'christchurch', 'pacific'],
            ],
            [
                'name' => 'Auckland Harbor Cam',
                'region' => 'North Island Coast',
                'country' => 'New Zealand',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/New-Zealand/Auckland/Auckland/webcams/1321300947',
                'latitude' => -36.8485,
                'longitude' => 174.7633,
                'status' => 'Pacific coastal watch',
                'risk_tier' => 3,
                'region_tags' => ['new zealand', 'auckland', 'pacific'],
            ],
            [
                'name' => 'Lisbon Coast Cam',
                'region' => 'Atlantic Margin',
                'country' => 'Portugal',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Portugal/Lisbon-District/Lisbon/webcams/1310889152',
                'latitude' => 38.7223,
                'longitude' => -9.1393,
                'status' => 'Atlantic coastal watch',
                'risk_tier' => 2,
                'region_tags' => ['portugal', 'lisbon', 'atlantic'],
            ],
            [
                'name' => 'Catania Coast Cam',
                'region' => 'Ionian Sicily Coast',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Sicily/Catania/webcams/1268909800',
                'latitude' => 37.5079,
                'longitude' => 15.0830,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'sicily', 'ionian', 'catania'],
            ],
            [
                'name' => 'Messina Strait Cam',
                'region' => 'Strait of Messina',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/sicilia/messina/porto-di-messina.html',
                'latitude' => 38.1938,
                'longitude' => 15.5540,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'messina', 'sicily', 'ionian'],
            ],
            [
                'name' => 'Reggio Calabria Cam',
                'region' => 'Calabria Strait Coast',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/calabria/reggio-calabria/lungomare.html',
                'latitude' => 38.1113,
                'longitude' => 15.6473,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 2,
                'region_tags' => ['italy', 'calabria', 'reggio', 'ionian'],
            ],
            [
                'name' => 'Naples Gulf Cam',
                'region' => 'Tyrrhenian Coast',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Campania/Naples/webcams/1268910024',
                'latitude' => 40.8518,
                'longitude' => 14.2681,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 1,
                'region_tags' => ['italy', 'naples', 'campania', 'tyrrhenian'],
            ],
            [
                'name' => 'Bari Coast Cam',
                'region' => 'Adriatic South Coast',
                'country' => 'Italy',
                'source' => 'SkylineWebcams',
                'stream_url' => 'https://www.skylinewebcams.com/en/webcam/italia/puglia/bari/lungomare.html',
                'latitude' => 41.1171,
                'longitude' => 16.8719,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 1,
                'region_tags' => ['italy', 'bari', 'adriatic', 'puglia'],
            ],
            [
                'name' => 'Ancona Harbor Cam',
                'region' => 'Central Adriatic Coast',
                'country' => 'Italy',
                'source' => 'Windy Webcams',
                'stream_url' => 'https://www.windy.com/-Webcams/Italy/Marche/Ancona/webcams/1268910341',
                'latitude' => 43.6158,
                'longitude' => 13.5189,
                'status' => 'Mediterranean coastal watch',
                'risk_tier' => 1,
                'region_tags' => ['italy', 'ancona', 'adriatic'],
            ],
        ],
    ],
    'bulletins' => [
        'provider' => 'Institutional Bulletins',
        'sources' => [
            [
                'key' => 'smithsonian_gvp',
                'label' => 'Smithsonian GVP',
                'category' => 'Volcano',
                'url' => 'https://volcano.si.edu/news/WeeklyVolcanoRSS.xml',
            ],
            [
                'key' => 'usgs_updates',
                'label' => 'USGS Updates',
                'category' => 'Earth Science',
                'url' => 'https://www.usgs.gov/feeds/news',
            ],
            [
                'key' => 'noaa_swpc',
                'label' => 'NOAA SWPC',
                'category' => 'Space Weather',
                'url' => 'https://www.swpc.noaa.gov/products-and-data/alerts-and-forecasts/rss',
            ],
        ],
    ],
];
