<?php
declare(strict_types=1);

return [
    'earthquakes' => [
        'provider' => 'USGS + INGV + EMSC',
        'sources' => [
            [
                'key' => 'usgs',
                'provider' => 'USGS',
                'url' => 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',
            ],
            [
                'key' => 'ingv',
                'provider' => 'INGV',
                'url' => 'https://webservices.ingv.it/fdsnws/event/1/query?format=geojson&limit=1000&orderby=time',
            ],
            [
                'key' => 'emsc',
                'provider' => 'EMSC',
                'url' => 'https://www.seismicportal.eu/fdsnws/event/1/query?format=json&limit=1000&orderby=time',
            ],
        ],
    ],
    'volcanoes' => [
        'provider' => 'Smithsonian GVP / USGS',
        'url' => 'https://volcano.si.edu/news/WeeklyVolcanoRSS.xml',
    ],
    'volcano_catalog' => [
        'provider' => 'Smithsonian GVP Volcanoes of the World',
        'url' => 'https://volcano.si.edu/database/list_volcano_holocene_excel.cfm',
    ],
    'volcano_current_eruptions' => [
        'provider' => 'Smithsonian GVP Current Eruptions',
        'url' => 'https://volcano.si.edu/gvp_currenteruptions.cfm',
    ],
    'tremors' => [
        'provider' => 'USGS (Tremor Signals Model)',
        'url' => 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',
    ],
    'tsunami' => [
        'provider' => 'NOAA / NWS',
        'url' => 'https://api.weather.gov/alerts/active?status=actual&message_type=alert',
    ],
    'space_weather' => [
        'provider' => 'NOAA SWPC',
        'kp_url' => 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',
        'kp_forecast_url' => 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json',
        'xray_url' => 'https://services.swpc.noaa.gov/json/goes/primary/xrays-1-day.json',
        'solar_wind_plasma_url' => 'https://services.swpc.noaa.gov/products/solar-wind/plasma-1-day.json',
        'solar_wind_mag_url' => 'https://services.swpc.noaa.gov/products/solar-wind/mag-1-day.json',
        'dst_url' => 'https://services.swpc.noaa.gov/products/kyoto-dst.json',
        'magnetometers_url' => 'https://services.swpc.noaa.gov/json/goes/primary/magnetometers-1-day.json',
        'auroral_oval_url' => 'https://services.swpc.noaa.gov/images/animations/ovation/north/latest.jpg',
        'sun_image_url' => 'https://services.swpc.noaa.gov/images/animations/suvi/primary/171/latest.png',
    ],
    'volcano_cams' => [
        'provider' => 'Curated Observatory Cameras',
        'items' => [
            [
                'name' => 'Etna Live Stream',
                'volcano' => 'Etna',
                'country' => 'Italy',
                'source' => 'INGV Catania',
                'stream_url' => 'https://www.ct.ingv.it/sezioniesterne/StreamingEtna.php',
                'embed_url' => 'https://garr.tv/videos/embed/c6c70a03-e711-4eed-9835-1d02f5a5ec58',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Stromboli Live',
                'volcano' => 'Stromboli',
                'country' => 'Italy',
                'source' => 'INGV Catania',
                'stream_url' => 'https://www.ct.ingv.it/sezioniesterne/StreamingEolie.php',
                'embed_url' => 'https://garr.tv/videos/embed/8790a7a8-211c-4794-bcb2-41e24cd2e322',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Popocatepetl',
                'volcano' => 'Popocatepetl',
                'country' => 'Mexico',
                'source' => 'CENAPRED',
                'stream_url' => 'https://www.cenapred.gob.mx/es/reportesVolcanesMX/',
                'embed_url' => 'http://www.atlasnacionalderiesgos.gob.mx/app/BoletinPopo/sync3.html',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Fuego',
                'volcano' => 'Fuego',
                'country' => 'Guatemala',
                'source' => 'Michigan Tech (with INSIVUMEH support)',
                'stream_url' => 'https://ovfuego-norte.geo.mtu.edu/animations.php',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea KWcam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/KWcam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/V1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V2cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/V2cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea V3cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/V3cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea B1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/B1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea F1cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/F1cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea K2cam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/observatories/hvo/cams/K2cam/images/M.jpg',
                'status' => 'Monitoring',
            ],
            [
                'name' => 'Kilauea KPcam',
                'volcano' => 'Kilauea',
                'country' => 'United States',
                'source' => 'USGS HVO',
                'stream_url' => 'https://www.usgs.gov/volcanoes/kilauea/summit-webcams',
                'snapshot_url' => 'https://volcanoes.usgs.gov/cams/KPcam/images/M.jpg',
                'status' => 'Monitoring',
            ],
        ],
    ],
    'bulletins' => [
        'provider' => 'Institutional Bulletins',
        'sources' => [
            [
                'key' => 'smithsonian_gvp',
                'label' => 'Smithsonian GVP',
                'category' => 'Volcano',
                'url' => 'https://volcano.si.edu/news/WeeklyVolcanoRSS.xml',
            ],
            [
                'key' => 'usgs_updates',
                'label' => 'USGS Updates',
                'category' => 'Earth Science',
                'url' => 'https://www.usgs.gov/feeds/news',
            ],
            [
                'key' => 'noaa_swpc',
                'label' => 'NOAA SWPC',
                'category' => 'Space Weather',
                'url' => 'https://www.swpc.noaa.gov/products-and-data/alerts-and-forecasts/rss',
            ],
        ],
    ],
];
